In [1]:
import numpy as np

In [ ]:
# 1. Array Creation
# Create the following NumPy arrays:

In [3]:
# QUESTION:1 - An array of integers from 1 to 10.

np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
# QUESTION:2 - An array of five zeros

np.zeros(5)

array([0., 0., 0., 0., 0.])

In [5]:
# QUESTION:3 - An array of five ones.

np.ones(5)

array([1., 1., 1., 1., 1.])

In [7]:
# QUESTION:4 - An array of even numbers from 2 to 20

np.arange(2,21,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [256]:
# 2. Array Properties
# Create a 3 × 4 NumPy array and find:
a=np.array([[1,2,3,4],[5,6,7,8],
           [9,10,11,12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [21]:
# QUESTION:1 - Shape

np.shape(a)

(3, 4)

In [22]:
# QUESTION:2 - Size

np.size(a)

12

In [261]:
# QUESTION:3 - Number of dimensions
a=np.array([[ 1,2,3,4],
 [ 5,6,7,8],
 [ 9,10,11,12]])
np.ndim(a)

2

In [30]:
# QUESTION:4 - Data type

type(a)

numpy.ndarray

In [27]:
# 3. Indexing and Slicing
# Given the array:
a=np.array([10, 20, 30, 40, 50, 60, 70, 80])
print(a)
# Perform the following:

[10 20 30 40 50 60 70 80]


In [37]:
# QUESTION:1 - Print the first element.

print(a[0])

10


In [39]:
# QUESTION:2 - Print the last element.

print(a[7])

80


In [40]:
# QUESTION:3 - Print elements from index 2 to 5.

print(a[2:6])

[30 40 50 60]


In [58]:
# QUESTION:4 - Print every alternate element.

print(a[::2])

[10 30 50 70]


In [149]:
# QUESTION:5 - Reverse the array

print(a[-1:-8])

[]


In [67]:
# 4. Reshaping Arrays
# Create an array containing numbers from 1 to 12.

a=np.arange(1,13)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [70]:
# QUESTION:1 - Convert it into a 3 × 4 matrix.

np.reshape(a,(3,4))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [71]:
# QUESTION:2 - Convert it into a 2 × 6 matrix

np.reshape(a,(2,6))

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [73]:
# 5. Arithmetic Operations
# Create two arrays:
A =np.array([1, 2, 3, 4, 5])
B =np.array([5, 4, 3, 2, 1])
print(A)
print(B)

[1 2 3 4 5]
[5 4 3 2 1]


In [92]:
# Perform:
# QUESTION:1 - Addition

np.add(A,B)

array([6, 6, 6, 6, 6])

In [78]:
# QUESTION:2 - Subtraction

np.subtract(A,B)

array([-4, -2,  0,  2,  4])

In [89]:
# QUESTION:3 - Multiplication

np.multiply(A,B)

array([5, 8, 9, 8, 5])

In [90]:
# QUESTION:4 - Division

np.divide(A,B)

array([0.2, 0.5, 1. , 2. , 5. ])

In [91]:
# 6. Statistical Functions
# Create an array:
a=np.array([12, 25, 18, 40, 30, 15])
print(a)

[12 25 18 40 30 15]


In [93]:
# Find:
# QUESTION:1 - Sum

np.sum(a)

np.int64(140)

In [94]:
# QUESTION:2 - Mean

np.mean(a)

np.float64(23.333333333333332)

In [95]:
# QUESTION:3 - Maximum

np.max(a)

np.int64(40)

In [96]:
# QUESTION:4 - Minimum

np.min(a)

np.int64(12)

In [97]:
# QUESTION:5 -  Standard deviation

np.std(a)

np.float64(9.585869229698938)

In [107]:
# 7. Random Arrays
# Create:
# A random array of 10 integers between 1 and 100.

a=np.arange(1,100,10)
print(a)

[ 1 11 21 31 41 51 61 71 81 91]


In [108]:
# QUESTION:1 - Find the largest value.

np.max(a)

np.int64(91)

In [109]:
# QUESTION:2 - Find the smallest value.

np.min(a)

np.int64(1)

In [111]:
# QUESTION:3 - Sort the array

np.sort(a)

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [113]:
# 8. Boolean Indexing
# Given the array:
b=np.array([5, 12, 18, 25, 30, 7, 40, 50])
print(b)

[ 5 12 18 25 30  7 40 50]


In [116]:
# QUESTION:1 - Print elements greater than 20.

c=b>20
print(c)

[False False False  True  True False  True  True]


In [126]:
# QUESTION:2 - Print even numbers.

print(b[b%2==0])

[12 18 30 40 50]


In [131]:
# QUESTION:3 - Count how many numbers are greater than 15.

c=b>15
print(c)

[False False  True  True  True False  True  True]


In [145]:
# 9. Matrix Operations
# QUESTION:1 - Create a 3 × 3 matrix.
c=np.arange(2,11)
print(c)

[ 2  3  4  5  6  7  8  9 10]


In [164]:
w=np.reshape(c,(3,3))

In [147]:
#QUESTION:2 -  Find its transpose.

np.transpose(c)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [180]:
# QUESTION:3 - Find the sum of each row.

#w[ s :e ,  s:e] 
print(w)

print("Row 1 sum:",w[0:1].sum())
print("Row 2 sum:",w[1:2].sum())
print("Row 3 sum:",w[2:3].sum())

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
Row 1 sum: 9
Row 2 sum: 18
Row 3 sum: 27


In [252]:
# QUESTION:4 - Find the sum of each column

print("column 1 sum:",w[:,0].sum())
print("column 2 sum:",w[:,1].sum())
print("column 3 sum:",w[:,2].sum())

column 1 sum: 15
column 2 sum: 18
column 3 sum: 21


In [150]:
# 10. Mini Practice Problem
# A student scored the following marks:
d=np.array([65, 72, 88, 45, 90, 55, 78, 84, 60, 95])
print(d)

[65 72 88 45 90 55 78 84 60 95]


In [151]:
# Perform the following:
# QUESTION:1 - Find the highest mark.

np.max(d)

np.int64(95)

In [152]:
# QUESTION:2 - Find the lowest mark.

np.min(d)

np.int64(45)

In [153]:
# QUESTION:1 - Calculate the average mark.

np.average(d)

np.float64(73.2)

In [154]:
# Display marks greater than 75.
e=d>75
print(e)

[False False  True False  True False  True  True False  True]


In [162]:
# Count the number of students who scored above 60.

f=len(d[d>60])
print(f)

7


In [160]:
# Sort the marks in ascending order

np.sort(a)

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])